### ISSUE TITLE
Error fetching trade 

### ISSUE THREAD

**Issue by lisabeyy** [arunkumar201/uniswap-widget-nextjs#1]
Still throwing the error "error fetching trade with latest version" 

 
![Uploading Screenshot 2024-05-29 at 12.45.41.png…]()

**Comment by arunkumar201** [comment]
No it is working in my browser 
try to connect with wallet as i used public rpc 
<img width="1710" alt="Screenshot 2024-05-30 at 6 11 24 AM" src="https://github.com/arunkumar201/uniswap-widget-nextjs/assets/70876302/ea582aea-6953-41ff-a680-16ec4a086b57">
